# Generated by Django 5.2.16 on 2026-08-04 02:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity_on_hand', models.IntegerField()),
                ('reorder_point', models.IntegerField()),
                ('reorder_quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'spare_parts',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('ISSUE', 'Issue'), ('ADJUSTMENT', 'Adjustment')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_movements',
            },
        ),
        migrations.CreateModel(
            name='BearingPartCompatibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bearing_model', models.CharField(max_length=255)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compatible_bearings', to='inventory.sparepart')),
            ],
            options={
                'db_table': 'bearing_part_compatibility',
            },
        ),
    ]
