# Generated by Django 5.2.16 on 2026-08-04 02:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('DIAGNOSTIC_PDF', 'Diagnostic PDF'), ('HISTORY_EXCEL', 'History Excel')], max_length=20)),
                ('params', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_jobs',
            },
        ),
    ]
