# Generated by Django 5.2.16 on 2026-08-04 02:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('machine_type', models.CharField(max_length=100)),
                ('criticality', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'machines',
            },
        ),
        migrations.CreateModel(
            name='Bearing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_label', models.CharField(max_length=100)),
                ('bearing_model', models.CharField(max_length=255)),
                ('ball_diameter_mm', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('pitch_diameter_mm', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('contact_angle_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('num_balls', models.IntegerField(blank=True, null=True)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=10)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bearings', to='registry.machine')),
            ],
            options={
                'db_table': 'bearings',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(choices=[('ACCELEROMETER', 'Accelerometer')], default='ACCELEROMETER', max_length=20)),
                ('axis', models.CharField(choices=[('RADIAL', 'Radial'), ('AXIAL', 'Axial')], max_length=10)),
                ('sample_rate_hz', models.IntegerField()),
                ('source', models.CharField(choices=[('SIMULATED', 'Simulated'), ('HARDWARE', 'Hardware')], default='SIMULATED', max_length=10)),
                ('mqtt_topic', models.CharField(max_length=255, unique=True)),
                ('bearing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensors', to='registry.bearing')),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
    ]
