# Generated by Django 5.2.16 on 2026-08-04 02:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VibrationWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField()),
                ('duration_s', models.DecimalField(decimal_places=3, max_digits=6)),
                ('num_samples', models.IntegerField()),
                ('waveform_path', models.CharField(max_length=500)),
                ('source_dataset', models.CharField(choices=[('CWRU', 'CWRU'), ('PU', 'Paderborn'), ('IMS', 'IMS'), ('SIMULATED_SYNTHETIC', 'Simulated Synthetic'), ('HARDWARE', 'Hardware')], max_length=25)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vibration_windows', to='registry.sensor')),
            ],
            options={
                'db_table': 'vibration_windows',
            },
        ),
    ]
