# Generated by Django 5.2.16 on 2026-08-04 02:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_type', models.CharField(choices=[('CLASSIFICATION', 'Classification'), ('RUL', 'Remaining Useful Life')], max_length=20)),
                ('fault_class', models.CharField(blank=True, choices=[('HEALTHY', 'Healthy'), ('INNER_RACE', 'Inner Race'), ('OUTER_RACE', 'Outer Race'), ('BALL', 'Ball'), ('UNKNOWN', 'Unknown')], max_length=20, null=True)),
                ('classification_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('predicted_rul_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rul_confidence_band_low_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rul_confidence_band_high_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('model_version', models.CharField(max_length=100)),
                ('predicted_at', models.DateTimeField()),
                ('bearing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='registry.bearing')),
                ('window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='ingestion.vibrationwindow')),
            ],
            options={
                'db_table': 'predictions',
            },
        ),
    ]
